services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:  # Verifica se o PostgreSQL está pronto
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5

  flyway:
    image: flyway/flyway:9.22.3
    command:
      - -url=jdbc:postgresql://postgres:5432/${DB_NAME}
      - -user=${DB_USER}
      - -password=${DB_PASSWORD}
      - -connectRetries=10
      - migrate
    volumes:
      - ./src/main/resources/db/migration:/flyway/sql  # Pasta dos scripts SQL
    depends_on:
      postgres:
        condition: service_healthy  # Só executa após o PostgreSQL estar pronto

  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/${DB_NAME}
    depends_on:
      - flyway  # A app só inicia após o Flyway migrar
    networks:
      - backend

volumes:
  postgres_data:

networks:
  backend:
    driver: bridge